/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Pandora.view.MyPanel', {
    extend: 'Pandora.view.ui.MyPanel',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },

    doStuff: function(a) {
        if (a === b) {
            // do stuff for rizza
        }
    }

});