/*
 * File: app/view/SongInfo.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Pandora.view.SongInfo', {
    extend: 'Pandora.view.ui.SongInfo',
    alias: 'widget.songinfo',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },

    doStuff: function(a) {
        if (a === b) {
            // do stuff for rizza
        }
    },

    update: function(record) {
        var data = record ? record.data : {};
        this.down('#songdescription').update(data);
        this.callParent([data]);
    }

});