/*
 * File: app/view/SongInfo.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.view.SongInfo', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.songinfo',


    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tpl: [
                '<h1>About {artist}</h1><p>{description}</p>'
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    height: 100,
                    layout: {
                        align: 'middle',
                        pack: 'end',
                        padding: '[0, 5]',
                        type: 'hbox'
                    },
                    dock: 'top',
                    items: [
                        {
                            xtype: 'component',
                            itemId: 'songdescription',
                            tpl: [
                                '<h2>{artist}</h2><h1>{name}</h1><h2>{album}</h2>'
                            ],
                            width: 200
                        },
                        {
                            xtype: 'button',
                            text: 'menu',
                            action: 'song-menu'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    update: function(record) {
        var data = record ? record.data : {};
        this.down('#songdescription').update(data);
        this.callParent([data]);
    }

});