/*
 * File: app/view/SongControls.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.view.SongControls', {
    extend: 'Ext.container.Container',
    alias: 'widget.songcontrols',

    height: 70,
    layout: {
        align: 'center',
        pack: 'center',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 30,
                    width: 300,
                    defaultType: 'button',
                    layout: {
                        align: 'middle',
                        pack: 'center',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Vote Down',
                            action: 'vote-down'
                        },
                        {
                            xtype: 'button',
                            text: 'Vote Up',
                            action: 'vote-up'
                        },
                        {
                            xtype: 'button',
                            text: 'Pause',
                            action: 'pause'
                        },
                        {
                            xtype: 'button',
                            text: 'Skip',
                            action: 'skip'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    width: 300,
                    layout: {
                        align: 'middle',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'component',
                            html: '2:00'
                        },
                        {
                            xtype: 'progressbar',
                            margin: '[0, 5]',
                            value: 0.5,
                            flex: 1
                        },
                        {
                            xtype: 'component',
                            html: '4:00'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});