/*
 * File: app/view/StationsList.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Pandora.view.StationsList', {
    extend: 'Pandora.view.ui.StationsList',
    alias: 'widget.stationslist',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }

});