/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.view.Viewport', {
    extend: 'Pandora.view.MyPanel',
    renderTo: Ext.getBody(),
    requires: [
        'Pandora.view.MyPanel',
        'Pandora.view.NewStation'
    ]
});