/*
 * File: app/model/MyModel1.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.model.MyModel1', {
    extend: 'Ext.data.Model'});