/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.model.MyModel', {
    extend: 'Ext.data.Model',

    pageSize: 99,
    remoteSort: true,
    sortOnFilter: false,

    items: [
        {
            fn: 'helloDonkey'
        }
    ],

    fields: [
        {
            name: 'abc'
        }
    ],

    belongsTo: {
        model: 'Pandora.model.MyModel'
    },

    hasMany: {

    },

    idgen: {
        type: 'uuid'
    },

    helloDonkey: function() {

    }
});