/*
 * File: app/view/ui/MyViewport.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.view.ui.MyViewport', {
    extend: 'Ext.container.Viewport',
    requires: [
        'Pandora.view.NewStation',
        'Pandora.view.SongControls',
        'Pandora.view.StationsList',
        'Pandora.view.RecentlyPlayedScroller',
        'Pandora.view.SongInfo'
    ],

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    height: 80,
                    flex: 1,
                    items: [
                        {
                            xtype: 'newstation',
                            width: 150
                        },
                        {
                            xtype: 'songcontrols',
                            flex: 1
                        },
                        {
                            xtype: 'component',
                            html: 'Pandora<br>Internet Radio'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    flex: 1,
                    items: [
                        {
                            xtype: 'panel',
                            id: 'west-region',
                            width: 250,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'stationslist',
                                    flex: 1
                                },
                                {
                                    xtype: 'panel',
                                    height: 250,
                                    html: 'Ad'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'east-region',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            flex: 1,
                            items: [
                                {
                                    xtype: 'recentlyplayedscroller',
                                    height: 250
                                },
                                {
                                    xtype: 'songinfo',
                                    flex: 1
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});