/*
 * File: app/view/ui/NewStation.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.view.ui.NewStation', {
    extend: 'Ext.form.field.ComboBox',

    fieldLabel: 'Label',
    emptyText: 'Search station',
    displayField: 'name',
    queryMode: 'local',
    store: 'SearchResults',
    valueField: 'id',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});