/*
 * File: app/view/ui/SongInfo.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.view.ui.SongInfo', {
    extend: 'Ext.panel.Panel',


    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tpl: Ext.create('Ext.XTemplate', 
                '<h1>About {artist}</h1><p>{description}</p>'
            ),
            dockedItems: [
                {
                    xtype: 'container',
                    height: 100,
                    layout: {
                        align: 'middle',
                        pack: 'end',
                        padding: '[0, 5]',
                        type: 'hbox'
                    },
                    dock: 'top',
                    items: [
                        {
                            xtype: 'component',
                            itemId: 'songdescription',
                            tpl: Ext.create('Ext.XTemplate', 
                                '<h2>{artist}</h2><h1>{name}</h1><h2>{album}</h2>'
                            ),
                            width: 200
                        },
                        {
                            xtype: 'button',
                            text: 'menu',
                            action: 'song-menu'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});