/*
 * File: designer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Station',
        'Song'
    ],
    stores: [
        'RecentSongs',
        'SearchResults',
        'Stations'
    ],
    autoCreateViewport: true,
    name: 'Pandora',

    controllers: [
        'Song',
        'Station'
    ],

    launch: function() {
        //do some stuff in here

    }
});
