/*
 * File: app/store/base/Stations.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.store.base.Stations', {
    extend: 'Ext.data.Store',
    requires: [
        'Pandora.model.Station'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Stations',
            model: 'Pandora.model.Station'
        }, cfg)]);
    }
});