/*
 * File: app/controller/Song.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Pandora.controller.Song', {
    extend: 'Ext.app.Controller',

    stores: [
        'RecentSongs'
    ],
    refs: [
        {
            ref: 'songInfo',
            selector: 'songinfo'
        },
        {
            ref: 'recentlyPlayedScroller',
            selector: 'recentlyplayedscroller'
        }
    ],

    init: function() {
        this.control({
            "recentlyplayedscroller": {
                selectionchange: this.onSongSelect
            }
        });
        this.application.on({
            stationstart: {
                fn: this.onStationStart,
                scope: this
            }
        });
    },

    onSongSelect: function(dataview, selections, options) {
        this.getSongInfo().update(selections[0]);
    },

    onStationStart: function(station) {
        var store = this.getRecentSongsStore();

        store.load({
            callback: this.onRecentSongsLoad,
                params: {
                    station: station.get('id')
                },
                scope: this
            });
        // more stuff;
    },

    onRecentSongsLoad: function(songs, request) {
        var store = this.getRecentSongsStore(),
            selModel = this.getRecentlyPlayedScroller().getSelectionModel();

        // The data should already be filtered on the serverside but since we
        // are loading static data we need to do this after we loaded all the data
        store.clearFilter();
        store.filter('station', request.params.station);
        store.sort('played_date', 'ASC');

        selModel.select(store.last());
    }

});