/*
 * File: app/controller/Station.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pandora.controller.Station', {
    extend: 'Ext.app.Controller',
    alias: 'controller.donkey',

    stores: [
        'Stations',
        'SearchResults'
    ],
    views: [
        'StationsList'
    ],
    refs: [
        {
            ref: 'stationsList',
            selector: 'stationslist'
        }
    ],

    init: function() {
        this.control({
            "stationslist": {
                selectionchange: this.onStationSelect
            },
            "newstation": {
                select: this.onNewStationSelect
            }
        });
    },

    onStationSelect: function(tablepanel, selections, options) {
        // Fire an application wide event
        this.application.fireEvent('stationstart', selections[0]);
    },

    onNewStationSelect: function(field, value, options) {
        var selected = value[0],
            store = this.getStationsStore(),
            list = this.getStationsList();

        if (selected && !store.getById(selected.get('id'))) {
            store.add(selected);
        }
        list.getSelectionModel().select(selected);
    },

    onLaunch: function() {
        var stationsStore = this.getStationsStore();
        stationsStore.load({
            callback: this.onStationsLoad,
            scope: this
        });
    },

    onStationsLoad: function() {
        var stationsList = this.getStationsList();
        console.log(this.getStationsList());
        stationsList.getSelectionModel().select(0);
    }

});